// Test generated by RoostGPT for test test-04-07-1 using AI Model vertex

package main

import (
	"fmt"
	"sort"
	"testing"
)

// UsersByAge is a type that implements the sort.Interface
type UsersByAge []User

// Len is part of the sort.Interface
func (u UsersByAge) Len() int {
	return len(u)
}

// Less is part of the sort.Interface
func (u UsersByAge) Less(i, j int) bool {
	return u[i].Age < u[j].Age
}

// Swap is part of the sort.Interface
func (u UsersByAge) Swap(i, j int) {
	u[i], u[j] = u[j], u[i]
}

func TestSwap082341d67f(t *testing.T) {
	// Test case 1: Swap two elements in the slice
	u := UsersByAge{
		User{Age: 10},
		User{Age: 20},
		User{Age: 30},
	}

	u.Swap(0, 1)

	if u[0].Age != 20 || u[1].Age != 10 {
		t.Error("Swap failed")
	}

	// Test case 2: Swap two elements that are not next to each other
	u = UsersByAge{
		User{Age: 10},
		User{Age: 20},
		User{Age: 30},
	}

	u.Swap(0, 2)

	if u[0].Age != 30 || u[2].Age != 10 {
		t.Error("Swap failed")
	}
}
