// Test generated by RoostGPT for test test-04-07-1 using AI Model vertex

package main

import (
	"fmt"
	"sort"
	"testing"
)

// UsersByAge is a type that implements the sort.Interface
type UsersByAge []User

// Less returns true if the User at index i is less than the User at index j
func (u UsersByAge) Less(i, j int) bool {
	return u[i].Age < u[j].Age
}

// TestLessb1dd685bd2 is a unit test case for the Less function
func TestLessb1dd685bd2(t *testing.T) {
	// Create a slice of Users
	users := []User{
		{Age: 10},
		{Age: 20},
		{Age: 30},
	}

	// Sort the slice by age
	sort.Sort(UsersByAge(users))

	// Verify that the slice is sorted correctly
	for i := 0; i < len(users)-1; i++ {
		if users[i].Age > users[i+1].Age {
			t.Error("The slice is not sorted correctly")
		}
	}
}
