// Test generated by RoostGPT for test test-04-07-1 using AI Model vertex

package main

import (
	"fmt"
	"sort"
	"testing"
)

// UsersByAge is a type that implements the sort.Interface
type UsersByAge []User

// Less returns true if the User at index i is less than the User at index j
func (u UsersByAge) Less(i, j int) bool {
	return u[i].Age < u[j].Age
}

// TestLessb1dd685bd2 tests the Less function
func TestLessb1dd685bd2(t *testing.T) {
	// Create a slice of Users
	users := []User{
		{Name: "John", Age: 20},
		{Name: "Mary", Age: 18},
		{Name: "Peter", Age: 25},
	}

	// Sort the slice by age
	sort.Sort(UsersByAge(users))

	// Verify that the slice is sorted correctly
	if users[0].Age != 18 {
		t.Error("Expected the first User to have an age of 18, but it was", users[0].Age)
	}
	if users[1].Age != 20 {
		t.Error("Expected the second User to have an age of 20, but it was", users[1].Age)
	}
	if users[2].Age != 25 {
		t.Error("Expected the third User to have an age of 25, but it was", users[2].Age)
	}
}
