// Test generated by RoostGPT for test test-04-07-1 using AI Model vertex

package main

import (
	"fmt"
	"testing"
)

func TestMain(t *testing.T) {
	// Test case 1: The slice of users is empty
	users := []User{}

	// Sort the slice of users by age
	sort.Sort(UsersByAge(users))

	// Check that the slice of users is still empty
	if len(users) != 0 {
		t.Error("The slice of users should be empty")
	}

	// Test case 2: The slice of users contains only one user
	users = []User{
		{
			Name: "Rajeev",
			Age:  28,
		},
	}

	// Sort the slice of users by age
	sort.Sort(UsersByAge(users))

	// Check that the slice of users is sorted correctly
	if users[0].Name != "Rajeev" || users[0].Age != 28 {
		t.Error("The slice of users is not sorted correctly")
	}

	// Test case 3: The slice of users contains multiple users
	users = []User{
		{
			Name: "Rajeev",
			Age:  28,
		},
		{
			Name: "Monica",
			Age:  31,
		},
		{
			Name: "John",
			Age:  56,
		},
		{
			Name: "Amanda",
			Age:  16,
		},
		{
			Name: "Steven",
			Age:  28,
		},
	}

	// Sort the slice of users by age
	sort.Sort(UsersByAge(users))

	// Check that the slice of users is sorted correctly
	if users[0].Name != "Amanda" || users[0].Age != 16 {
		t.Error("The slice of users is not sorted correctly")
	}
}
