// Test generated by RoostGPT for test test-04-07-1 using AI Model vertex

package main

import (
	"fmt"
	"testing"
)

func TestMain(t *testing.T) {
	// Test case 1: Sorting a slice of strings in reverse order
	strs := []string{"quick", "brown", "fox", "jumpes"}
	sort.Sort(sort.Reverse(sort.StringSlice(strs)))
	if strs[0] != "jumpes" {
		t.Error("Expected first element to be 'jumpes', but got '" + strs[0] + "'")
	}

	// Test case 2: Sorting a slice of integers in reverse order
	ints := []int{56, 19, 78, 67, 14, 25}
	sort.Sort(sort.Reverse(sort.IntSlice(ints)))
	if ints[0] != 78 {
		t.Error("Expected first element to be 78, but got " + ints[0])
	}

	// Test case 3: Sorting a slice of floats in reverse order
	floats := []float64{176.8, 19.5, 20.8, 57.4}
	sort.Sort(sort.Reverse(sort.Float64Slice(floats)))
	if floats[0] != 57.4 {
		t.Error("Expected first element to be 57.4, but got " + floats[0])
	}
}
