// Test generated by RoostGPT for test test-04-07-1 using AI Model vertex

package main

import (
	"fmt"
	"testing"
)

func TestMain(t *testing.T) {
	// Test case 1: Sorting a slice of strings
	strs := []string{"quick", "brown", "fox", "jumpes"}
	sort.Strings(strs)
	if strs[0] != "brown" {
		t.Error("The slice was not sorted correctly.")
	}

	// Test case 2: Sorting a slice of integers
	ints := []int{56, 19, 78, 67, 14, 25}
	sort.Ints(ints)
	if ints[0] != 14 {
		t.Error("The slice was not sorted correctly.")
	}

	// Test case 3: Sorting a slice of floats
	floats := []float64{176.8, 19.5, 20.8, 57.4}
	sort.Float64s(floats)
	if floats[0] != 19.5 {
		t.Error("The slice was not sorted correctly.")
	}
}
